---

- name: "create openldap dir"
  file:
    path: "{{ openldap_dir }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_group }}"

- name: "template users ldif file"
  template:
    src: "users.ldif.j2"
    dest: "{{ users_ldif_location }}"
    owner: "{{ user_group.openldapconfig.uid }}"
    group: "{{ user_group.openldapconfig.gid }}"
    mode: "600"

- name: "template admin ldif file"
  template:
    src: "admin.ldif.j2"
    dest: "{{ admin_ldif_location }}"
    owner: "{{ user_group.openldapconfig.uid }}"
    group: "{{ user_group.openldapconfig.gid }}"
    mode: "600"

- name: "template groups ldif file"
  template:
    src: "groups.ldif.j2"
    dest: "{{ groups_ldif_location }}"
    owner: "{{ user_group.openldapconfig.uid }}"
    group: "{{ user_group.openldapconfig.gid }}"
    mode: "600"

- name: "template admin group ldif file"
  template:
    src: "admin_group.ldif.j2"
    dest: "{{ admin_group_ldif_location }}"
    owner: "{{ user_group.openldapconfig.uid }}"
    group: "{{ user_group.openldapconfig.gid }}"
    mode: "600"

- name: "deploy openldap"
  docker_container:
    name: "openldap"
    image: "osixia/openldap:{{ app_versions.openldap }}"
    env:
      LDAP_ORGANISATION: "{{ organization }}"
      LDAP_DOMAIN: "{{ domain }}"
      LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
      LDAP_TLS: "false"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "{{ ldap_readonly_user }}"
      LDAP_READONLY_USER_PASSWORD: "{{ ldap_readonly_password }}"
      LDAP_OPENLDAP_UID: "{{ user_group.openldapconfig.uid }}"
      LDAP_OPENLDAP_GID: "{{ user_group.openldapconfig.gid }}"
    networks: "{{ all_docker_networks }}"
    purge_networks: yes
    detach: true
    restart_policy: "always"
    volumes:
      - "{{ docker_volumes.openldapdata }}:/var/lib/ldap"
      - "{{ docker_volumes.openldapconfig }}:/etc/ldap/slapd.d"
      - "{{ openldap_dir }}:/ldif"
    networks_cli_compatible: no
    container_default_behavior: compatibility

- name: "wait for ldap to come up + become searchable"
  shell:
    cmd: "docker exec openldap 'ldapsearch' '-x' '-H' 'ldap://localhost' '-b' '{{ ldap_base_dn }}' '-D' '{{ ldap_admin_dn }}' -w '{{ ldap_admin_password }}'"
  register: ldap_search_output
  until: ldap_search_output.rc == 0
  changed_when: false
  ignore_errors: yes
  retries: 10
  delay: 5

- name: "init users"
  shell:
    cmd: "docker exec openldap 'ldapadd' '-x' '-H' 'ldap://localhost' '-D' '{{ ldap_admin_dn }}' -w '{{ ldap_admin_password }}' '-f' '/ldif/users.ldif'"
  register: ldap_add_output
  until: "ldap_add_output.rc == 68"
  failed_when: "ldap_add_output.rc not in [ 0, 68 ]"
  changed_when: "ldap_add_output.rc == 0"
  retries: 10
  delay: 5

- name: "init admin"
  shell:
    cmd: "docker exec openldap 'ldapadd' '-x' '-H' 'ldap://localhost' '-D' '{{ ldap_admin_dn }}' -w '{{ ldap_admin_password }}' '-f' '/ldif/admin.ldif'"
  register: ldap_add_output
  until: "ldap_add_output.rc == 68"
  failed_when: "ldap_add_output.rc not in [ 0, 68 ]"
  changed_when: "ldap_add_output.rc == 0"
  retries: 10
  delay: 5

- name: "init groups"
  shell:
    cmd: "docker exec openldap 'ldapadd' '-x' '-H' 'ldap://localhost' '-D' '{{ ldap_admin_dn }}' -w '{{ ldap_admin_password }}' '-f' '/ldif/groups.ldif'"
  register: ldap_add_output
  until: "ldap_add_output.rc == 68"
  failed_when: "ldap_add_output.rc not in [ 0, 68 ]"
  changed_when: "ldap_add_output.rc == 0"
  retries: 10
  delay: 5

- name: "init admin_group"
  shell:
    cmd: "docker exec openldap 'ldapadd' '-x' '-H' 'ldap://localhost' '-D' '{{ ldap_admin_dn }}' -w '{{ ldap_admin_password }}' '-f' '/ldif/admin_group.ldif'"
  register: ldap_add_output
  until: "ldap_add_output.rc == 68"
  failed_when: "ldap_add_output.rc not in [ 0, 68 ]"
  changed_when: "ldap_add_output.rc == 0"
  retries: 10
  delay: 5
