### THIS IS AN EXAMPLE
### To use it, move it to the base dir of this repo, and change the ansible_host and ansible_user to correct values for your server

all:
  hosts:
    content_server_1:
      ansible_connection: ssh
      ansible_port: 22
      ansible_host: 101.102.103.104
      ansible_user: some_username
