---

- name: "create nginx dir"
  file:
    path: "{{ nginx_dir }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_group }}"

- name: "template nginx config file"
  template:
    src: "nginx.conf.j2"
    dest: "{{ synapse_nginx_config_file }}"
    owner: "{{ user_group.nginx.uid }}"
    group: "{{ user_group.nginx.gid }}"
    mode: "600"
  notify:
    - "restart synapse nginx"

- name: "deploy nginx"
  docker_container:
    name: "matrix_nginx"
    image: "nginx:{{ app_versions.nginx }}"
    log_driver: "local"
    networks:
      - name: "{{ docker_network_names.synapse }}"
    purge_networks: yes
    detach: true
    restart_policy: "always"
    volumes:
      - "{{ synapse_nginx_config_file }}:/etc/nginx/nginx.conf"
    networks_cli_compatible: no
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.services.nginx-synapse.loadbalancer.server.port: "80"
      traefik.http.routers.nginx-synapse_https.rule: "(Host(`{{ domain }}`) && PathPrefix(`/.well-known/matrix/server`)) || (Host(`{{ domain }}`) && PathPrefix(`/.well-known/matrix/client`))"
      traefik.http.routers.nginx-synapse_https.tls: "true"
      traefik.http.routers.nginx-synapse_https.tls.certresolver: "le"
      traefik.http.routers.nginx-synapse_https.entrypoints: "websecure"
      traefik.http.routers.nginx-synapse_https.service: "nginx-synapse"
