---

- name: "create synapse dir"
  file:
    path: "{{ synapse_dir }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_group }}"

- name: "template synapse config file"
  template:
    src: "config.yaml.j2"
    dest: "{{ synapse_config_file }}"
    owner: "{{ user_group.synapse.uid }}"
    group: "{{ user_group.synapse.gid }}"
    mode: "600"
  notify:
    - "restart synapse"

- name: "deploy synapse"
  docker_container:
    name: "synapse"
    image: "matrixdotorg/synapse:{{ app_versions.synapse }}"
    networks:
      - name: "{{ docker_network_names.synapse }}"
    purge_networks: yes
    detach: true
    restart_policy: "always"
    volumes:
      - "{{ synapse_config_file }}:/data/homeserver.yaml"
      - "{{ docker_volumes.synapse }}:/data"
    networks_cli_compatible: no
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.services.synapse-synapse.loadbalancer.server.port: "8008"
      traefik.http.routers.synapse_https.rule: "Host(`{{ synapse_hostname }}`)"
      traefik.http.routers.synapse_https.tls: "true"
      traefik.http.routers.synapse_https.entrypoints: "websecure"
      traefik.http.routers.synapse_https.service: "synapse-synapse"
