---

openldap_dir: "{{ top_level_dir }}/openldap"
initial_ldif_location: "{{ openldap_dir }}/initial.ldif"
ldap_readonly_user: "ldapreadonly"
ldap_base_dn: "dc={{ organization }},dc={{ top_level_domain }}"
ldap_admin_dn: "cn=admin,{{ ldap_base_dn }}"
