---

openldap_dir: "{{ top_level_dir }}/openldap"
container_ldif_location: "{{ openldap_dir }}/container.ldif"
admin_ldif_location: "{{ openldap_dir }}/admin.ldif"

ldap_base_dn: "dc={{ organization }},dc={{ top_level_domain }}"
ldap_users_dn: "ou=users,{{ ldap_base_dn }}"
ldap_groups_dn: "ou=groups,{{ ldap_base_dn }}"
ldap_admins_group_dn: "cn=admins,{{ ldap_groups_dn }}"

ldap_admin_dn: "cn=admin,{{ ldap_base_dn }}"

ldap_readonly_user: "ldapreadonly"
ldap_readonly_user_dn: "cn={{ ldap_readonly_user }},{{ ldap_base_dn }}"

ldap_admin_user: "admin"
ldap_admin_user_dn: "uid={{ ldap_admin }},{{ ldap_users_dn }}"
