---

peertube_rtmp_port: "1935"

peertube_dir: "{{ top_level_dir }}/peertube"
peertube_env_file: "{{ peertube_dir }}/env"
peertube_production_config: "/var/lib/docker/volumes/{{ docker_volumes.peertube_config }}/_data/production.yaml"
