---

synapse_dir: "{{ top_level_dir }}/synapse"
synapse_config_file: "/var/lib/docker/volumes/{{ docker_volumes.synapse }}/_data/homeserver.yaml"

synapse_postgres_user: "synapse"
synapse_postgres_db: "synapse"
