---

- name: "deploy dex"
  docker_container:
    name: "dex"
    image: "ghcr.io/dexidp/dex:{{ app_versions.dex }}"
    env:
      TODO: AHHH
    networks:
      - name: "{{ docker_network_names.dex }}"
    purge_networks: yes
    detach: true
    restart_policy: "always"
    volumes:
      - "{{ docker_volumes.dex }}:/???????????????"
    networks_cli_compatible: no
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.services.dex.loadbalancer.server.port: "?????"
      traefik.http.routers.dex_https.rule: "Host(`{{ dex_hostname }}`)"
      traefik.http.routers.dex_https.tls: "true"
      traefik.http.routers.dex_https.tls.certresolver: "le"
      traefik.http.routers.dex_https.entrypoints: "websecure"
