---

- name: "create certs dir"
  file:
    path: "{{ certs_dir }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_group }}"

- name: create CA key
  openssl_privatekey:
    path: "{{ ca_key_path }}"
  register: ca_key

- name: create the CA CSR
  openssl_csr:
    path: "{{ ca_csr_path }}"
    privatekey_path: "{{ ca_key.filename }}"
    common_name: "{{ organization }}-ca"
    basic_constraints:
      - "CA:TRUE"
  register: ca_csr

- name: sign the CA CSR
  openssl_certificate:
    path: "{{ ca_crt_path }}"
    csr_path: "{{ ca_csr.filename }}"
    privatekey_path: "{{ ca_key.filename }}"
    provider: selfsigned
  register: ca_crt
