---

########################
### SYNAPSE HANDLERS ###
########################
- name: "restart synapse"
  docker_container:
    name: "synapse"
    state: "started"
    restart: true

- name: "restart element"
  docker_container:
    name: "element"
    state: "started"
    restart: true

- name: "restart synapse nginx"
  docker_container:
    name: "matrix_nginx"
    state: "started"
    restart: true

########################
### TRAEFIK HANDLERS ###
########################
- name: "restart traefik"
  docker_container:
    name: "traefik"
    state: "started"
    restart: true

########################
##### DEX HANDLERS #####
########################
- name: "restart dex"
  docker_container:
    name: "dex"
    state: "started"
    restart: true

########################
##### GTS HANDLERS #####
########################
- name: "restart gotosocial"
  docker_container:
    name: "gotosocial"
    state: "started"
    restart: true

- name: "restart gotosocial nginx"
  docker_container:
    name: "gotosocial_nginx"
    state: "started"
    restart: true

##########################
##### REDIS HANDLERS #####
##########################
- name: "restart redis"
  docker_container:
    name: "redis"
    state: "started"
    restart: true
