---

- name: "template minio config"
  template:
    src: "minio.env"
    dest: "{{ minio_config_file }}"
    owner: "{{ user_group.minio.uid }}"
    group: "{{ user_group.minio.gid }}"
    mode: "600"

- name: "deploy minio"
  docker_container:
    name: "minio"
    image: "minio/minio:{{ app_versions.minio }}"
    pull: true
    log_driver: "local"
    command: ["server", "--console-address", ":9001"]
    env:
      MINIO_HOSTNAME: "{{ minio_hostname }}"
      MINIO_VOLUMES: "{{ minio_volumes }}"
      MINIO_CONFIG_ENV_FILE: "{{ minio_config_file_dest }}"
    networks:
      - name: "{{ docker_network_names.minio }}"
    purge_networks: yes
    detach: true
    restart_policy: "always"
    user: "{{ user_group.minio.uid }}:{{ user_group.minio.gid }}"
    volumes:
      - "{{ docker_volumes.minio }}:{{ minio_volumes }}"
    networks_cli_compatible: no
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      
      # CONSOLE
      traefik.http.services.minio_console.loadbalancer.server.port: "9001"
      traefik.http.routers.minio_console_https.rule: "Host(`{{ minio_console_hostname }}`)"
      traefik.http.routers.minio_console_https.tls: "true"
      traefik.http.routers.minio_console_https.tls.certresolver: "le"
      traefik.http.routers.minio_console_https.entrypoints: "websecure"
      traefik.http.routers.minio_console_https.service: "minio_console"

      # API
      traefik.http.services.minio_api.loadbalancer.server.port: "9000"
      traefik.http.routers.minio_api_https.rule: "Host(`{{ minio_hostname }}`)"
      traefik.http.routers.minio_api_https.tls: "true"
      traefik.http.routers.minio_api_https.tls.certresolver: "le"
      traefik.http.routers.minio_api_https.entrypoints: "websecure"
      traefik.http.routers.minio_api_https.service: "minio_api"
